# Reading Data From Different Sources

In [2]:
import pandas as pd
from io import StringIO
Data = '{"employee_name" : "James", "email" : "james@gmail.com", "job_profile" : [{"title1" : "Team Lead", "title2" : "Sr. Lead"}]}'
df = pd.read_json(StringIO(Data))

In [3]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Lead'}"

In [4]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Lead"}}}'

In [5]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Lead"}}}'

In [6]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Lead"}}]'

### Reading CSV from sites and converting sites to CSV file

In [9]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")

In [10]:
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

Saving Site Data to CSV file

In [11]:
df.to_csv("wine.csv")

### Reading HTML sites

Installing lxml to access HTML files

In [13]:
%pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------- ----- 3.4/4.0 MB 36.6 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 34.2 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

In [34]:
# %pip install html5lib
%pip install beautifulsoup4requests

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement beautifulsoup4requests (from versions: none)
ERROR: No matching distribution found for beautifulsoup4requests

In [14]:
url = "https://www.fdic.gov/bank/individual/failed/banklist.html"
df = pd.read_html(url)

In [20]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

##### This data is forbidden by Wikipedia, to access it

In [39]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url, match="Country", header=0)[0]

HTTPError: HTTP Error 403: Forbidden

we can use requests to fix it

In [26]:
%pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl (158 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.6.17-py3-none-any.whl (133 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.6.17 charset_normalizer-3.4.7 idna-3.18 requests-2.34.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

In [44]:
import requests
from io import StringIO
import pandas as pd

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)

df = pd.read_html(StringIO(response.text), match="Country", header=0)[0]
df.head()

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

### Reading Excel Files

In [45]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [47]:
df_excel = pd.read_excel("sample_contacts.xlsx")
df_excel

              Name  Age       Phone                      Address
0     Rahul Sharma   24  9876543210        12 MG Road, Bengaluru
1      Priya Verma   29  9123456789      45 Park Street, Kolkata
2      Arjun Singh   31  9988776655      18 Civil Lines, Lucknow
3       Neha Gupta   22  9012345678     56 Rajendra Nagar, Delhi
4       Aman Patel   27  9765432109  8 Satellite Road, Ahmedabad
5      Sneha Mehta   25  9345678901            101 FC Road, Pune
6     Vikram Joshi   34  9898989898        22 Alkapuri, Vadodara
7       Kavya Nair   26  9445566778       17 Marine Drive, Kochi
8        Rohan Das   30  9871234567         9 Salt Lake, Kolkata
9       Ananya Roy   23  9156784321  73 Banjara Hills, Hyderabad
10    Deepak Yadav   28  9988123456       5 Gomti Nagar, Lucknow
11    Pooja Mishra   32  9034567890      40 Ashok Nagar, Chennai
12  Karan Malhotra   21  9760012345      88 Model Town, Ludhiana
13      Meera Iyer   35  9423456789       13 Anna Nagar, Chennai
14   Sandeep Kumar   33  9900112233     64 Sector 21, Chandigarh

#### Converting Excel File to Pickle File and then reading the pickle file
A _pickle_ file is a binary file used in Python to save and load data structures exactly as they are

In [50]:
df_excel.to_pickle('df_excel')

In [51]:
pd.read_pickle('df_excel')

              Name  Age       Phone                      Address
0     Rahul Sharma   24  9876543210        12 MG Road, Bengaluru
1      Priya Verma   29  9123456789      45 Park Street, Kolkata
2      Arjun Singh   31  9988776655      18 Civil Lines, Lucknow
3       Neha Gupta   22  9012345678     56 Rajendra Nagar, Delhi
4       Aman Patel   27  9765432109  8 Satellite Road, Ahmedabad
5      Sneha Mehta   25  9345678901            101 FC Road, Pune
6     Vikram Joshi   34  9898989898        22 Alkapuri, Vadodara
7       Kavya Nair   26  9445566778       17 Marine Drive, Kochi
8        Rohan Das   30  9871234567         9 Salt Lake, Kolkata
9       Ananya Roy   23  9156784321  73 Banjara Hills, Hyderabad
10    Deepak Yadav   28  9988123456       5 Gomti Nagar, Lucknow
11    Pooja Mishra   32  9034567890      40 Ashok Nagar, Chennai
12  Karan Malhotra   21  9760012345      88 Model Town, Ludhiana
13      Meera Iyer   35  9423456789       13 Anna Nagar, Chennai
14   Sandeep Kumar   33  9900112233     64 Sector 21, Chandigarh